name: Rust

on:
  push:
    branches: [main, 0.*.x, 1.*.x]
  pull_request:
    branches: [main, 0.*.x, 1.*.x]

env:
  CARGO_TERM_COLOR: always
  REDISRS_REDIS_JSON_PATH: "/tmp/librejson.so"

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id || github.ref }}"
  cancel-in-progress: true

jobs:
  windows-build:
    needs: []
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install OpenSSL
        shell: powershell
        run: |
          vcpkg install openssl:x64-windows
          echo "OPENSSL_DIR=C:\vcpkg\packages\openssl_x64-windows" >> $env:GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=C:\vcpkg\packages\openssl_x64-windows\include" >> $env:GITHUB_ENV
          echo "OPENSSL_LIB_DIR=C:\vcpkg\packages\openssl_x64-windows\lib" >> $env:GITHUB_ENV

      - name: lint
        uses: ./.github/actions/lint-and-check
        with:
          rust-toolchain: stable
